### ISSUE TITLE
Unexpected response type 48

### ISSUE THREAD

**Issue by 8191** [sbjorn/vici#2]
When executing the following code on my machine I receive a `SessionException`:

``` python
import vici
s = vici.Session()
sas = s.list_sas()
sas.next()
```

``` python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vici/session.py", line 334, in streamed_request
    self._register_unregister(event_stream_type, False);
  File "vici/session.py", line 250, in _register_unregister
    confirm=Packet.EVENT_CONFIRM,
vici.exception.SessionException: Unexpected response type 46, expected '5' (EVENT_CONFIRM)
```

`ipsec status` lists some valid SAs.

Using Python 2.7.11 under FreeBSD 10.1.

**Comment by 8191** [comment]
Just saw that the project has moved away.
